export * from './customer.interface';
export * from './transporter.interface';
export * from './reciever.interface';
export * from './report.interface';
export * from './vessel.interface';
export * from './waste.interface';
export * from './article.interface';
export * from './user.interface';
export * from './region.interface';
